version: '3.9'

services:
  backend:
    image: leminhquangdev/airbnb-backend:latest
    container_name: cons-airbnb-backend
    ports:
      - '3001:3000'
    env_file:
      - .env
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8
    container_name: cons-airbnb-mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: airbnb_db
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
