name: CD-DOCKER

on:
  workflow_run:
    workflows: ['CI-DOCKER']
    types:
      - completed

jobs:
  build:
    runs-on: node_46

    steps:
      - name: Xóa file .env cũ
        run: sudo rm -rf .env

      - name: Tạo file .env mới
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> .env
          echo "ACCESS_TOKEN_EXPIRED=${{ secrets.ACCESS_TOKEN_EXPIRED }}" >> .env
          echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> .env
          echo "REFRESH_TOKEN_EXPIRED=${{ secrets.REFRESH_TOKEN_EXPIRED }}" >> .env
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> .env
          echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> .env
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env

      - name: Dừng container đang chạy
        run: sudo docker container stop cons-airbnb-backend || true

      - name: Xóa container cũ
        run: sudo docker container remove cons-airbnb-backend || true

      - name: Xóa image cũ
        run: sudo docker image remove leminhquangdev/airbnb-backend:latest || true

      - name: Chạy lại docker-compose
        run: sudo docker-compose up -d
